# Generated by Django 5.2.6 on 2026-02-05 00:00

from django.db import migrations, models
import django.db.models.deletion


try:
    from pgvector.django import VectorField
    embedding_field = VectorField(dimensions=768)
except ImportError:  # pragma: no cover - optional dependency
    from django.contrib.postgres.fields import ArrayField

    embedding_field = ArrayField(models.FloatField(), size=768)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("biblioteca", "0006_trabajoinvestigacion_contenido"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThesisEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding", embedding_field),
                (
                    "embedding_model",
                    models.CharField(
                        default="models/text-embedding-004",
                        max_length=100,
                    ),
                ),
                ("indexed_text", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trabajo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ia_embedding",
                        to="biblioteca.trabajoinvestigacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thesis Embedding",
                "verbose_name_plural": "Thesis Embeddings",
                "ordering": ["-updated_at"],
            },
        ),
    ]
