# Generated by Django 5.2.6 on 2026-06-26 11:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('requisitos', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('en_gracia', 'En Gracia'), ('oculta', 'Oculta')], default='vigente', max_length=20)),
                ('imagen_adjunta', models.ImageField(blank=True, null=True, upload_to='convocatorias/imagenes/')),
                ('documento_adjunto', models.FileField(blank=True, null=True, upload_to='convocatorias/documentos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MaterialBibliografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=500)),
                ('autor_texto', models.TextField()),
                ('anio_publicacion', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('resumen', models.TextField()),
                ('signatura_topografica', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material Bibliografico',
                'verbose_name_plural': 'Materiales Bibliograficos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario_tipo', models.CharField(choices=[('usuario', 'Usuario'), ('rol', 'Rol')], max_length=20)),
                ('destinatario_id', models.PositiveIntegerField()),
                ('origen_tipo', models.CharField(choices=[('aporte', 'Aporte'), ('prestamo', 'Prestamo')], max_length=20)),
                ('origen_id', models.PositiveIntegerField()),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PalabraClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Palabra Clave',
                'verbose_name_plural': 'Palabras Clave',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('puede_gestionar_usuarios', models.BooleanField(default=False)),
                ('puede_eliminar_contenido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('organizacion_origen', models.CharField(default='No especificado', max_length=200)),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(upload_to='aportes/%Y/%m/')),
                ('archivo_hash', models.CharField(blank=True, db_index=True, help_text='Hash MD5 del archivo para detectar duplicados', max_length=64)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de verificacion'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('motivo_rechazo', models.CharField(blank=True, choices=[('duplicado', 'Documento duplicado'), ('formato_incorrecto', 'Formato incorrecto'), ('contenido_no_academico', 'Contenido no academico')], max_length=50, null=True)),
                ('comentario_rechazo', models.TextField(blank=True, help_text='Comentario adicional sobre el rechazo', null=True)),
                ('revisado_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aportes_revisados', to=settings.AUTH_USER_MODEL)),
                ('usuario_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Aporte',
                'verbose_name_plural': 'Documentos Aporte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoConvocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='biblioteca.convocatoria')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('materialbibliografico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioteca.materialbibliografico')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('editorial', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_edicion', models.PositiveSmallIntegerField(default=1)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
            bases=('biblioteca.materialbibliografico',),
        ),
        migrations.CreateModel(
            name='TrabajoInvestigacion',
            fields=[
                ('materialbibliografico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioteca.materialbibliografico')),
                ('contenido', models.TextField(blank=True)),
                ('asesor_texto', models.CharField(max_length=255)),
                ('archivo_ruta', models.FileField(blank=True, null=True, upload_to='documentos/%Y/%m/')),
                ('tiene_archivo_digital', models.BooleanField(default=False)),
                ('especialidad', models.CharField(blank=True, max_length=255, null=True)),
                ('fuente_fisica', models.CharField(blank=True, max_length=255, null=True)),
                ('permite_preview_publico', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Trabajo de Investigacion',
                'verbose_name_plural': 'Trabajos de Investigacion',
            },
            bases=('biblioteca.materialbibliografico',),
        ),
        migrations.CreateModel(
            name='HistorialVisualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visualizacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_visualizaciones', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_visualizaciones', to='biblioteca.materialbibliografico')),
            ],
            options={
                'verbose_name': 'Historial de Visualizacion',
                'verbose_name_plural': 'Historial de Visualizaciones',
                'ordering': ['-fecha_visualizacion'],
            },
        ),
        migrations.CreateModel(
            name='CreditoDescarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_externo', models.EmailField(blank=True, max_length=254, null=True)),
                ('token_acceso', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditos_descarga', to=settings.AUTH_USER_MODEL)),
                ('aporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='biblioteca.documentoaporte')),
                ('usado_para', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_descarga', to='biblioteca.materialbibliografico')),
            ],
            options={
                'verbose_name': 'Credito de Descarga',
                'verbose_name_plural': 'Creditos de Descarga',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblioteca.rol')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='SolicitudPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('devuelta', 'Devuelta')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_prestamo', to=settings.AUTH_USER_MODEL)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_prestamo', to='biblioteca.libro')),
            ],
            options={
                'verbose_name': 'Solicitud de Prestamo',
                'verbose_name_plural': 'Solicitudes de Prestamo',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='AccesoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_acceso', models.CharField(db_index=True, max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesos_externos', to='biblioteca.materialbibliografico')),
            ],
            options={
                'verbose_name': 'Acceso Externo',
                'verbose_name_plural': 'Accesos Externos',
                'unique_together': {('token_acceso', 'material')},
            },
        ),
        migrations.CreateModel(
            name='PaginaPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to='paginas_pdf/%Y/%m/')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='biblioteca.materialbibliografico')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('material', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='MaterialBibliograficoPalabraClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_palabras_clave', to='biblioteca.materialbibliografico')),
                ('palabra_clave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_materiales', to='biblioteca.palabraclave')),
            ],
            options={
                'verbose_name': 'Relacion Material - Palabra Clave',
                'verbose_name_plural': 'Relaciones Material - Palabra Clave',
                'unique_together': {('material', 'palabra_clave')},
            },
        ),
    ]
