# Generated by Django 5.2.6 on 2025-12-03 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_convocatoria_clasificacion_codigo_cutter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajoinvestigacion',
            name='asesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_asesorados', to='biblioteca.autor'),
        ),
    ]
