# Generated by Django 5.2.6 on 2025-12-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_trabajoinvestigacion_asesor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='autortrabajo',
            options={'ordering': ['orden'], 'verbose_name': 'Autor de Trabajo', 'verbose_name_plural': 'Autores de Trabajos'},
        ),
        migrations.AlterModelOptions(
            name='clasificacion',
            options={'verbose_name': 'Clasificación', 'verbose_name_plural': 'Clasificaciones'},
        ),
        migrations.AlterModelOptions(
            name='convocatoria',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Convocatoria', 'verbose_name_plural': 'Convocatorias'},
        ),
        migrations.AlterModelOptions(
            name='historialvisualizacion',
            options={'ordering': ['-fecha_visualizacion'], 'verbose_name': 'Historial de Visualización', 'verbose_name_plural': 'Historial de Visualizaciones'},
        ),
        migrations.AlterModelOptions(
            name='palabraclave',
            options={'ordering': ['termino'], 'verbose_name': 'Palabra Clave', 'verbose_name_plural': 'Palabras Clave'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['nombre'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='solicitudprestamo',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Solicitud de Préstamo', 'verbose_name_plural': 'Solicitudes de Préstamo'},
        ),
        migrations.AlterModelOptions(
            name='trabajoinvestigacion',
            options={'ordering': ['-fecha_publicacion', '-created_at'], 'verbose_name': 'Trabajo de Investigación', 'verbose_name_plural': 'Trabajos de Investigación'},
        ),
        migrations.AddField(
            model_name='rol',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_aprobar_prestamos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_eliminar_contenido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_gestionar_usuarios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_ver_estadisticas',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trabajoinvestigacion',
            name='carrera',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trabajoinvestigacion',
            name='fecha_publicacion',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='trabajoinvestigacion',
            name='tipo_material',
            field=models.CharField(choices=[('articulo', 'Artículo'), ('tesis', 'Tesis'), ('libro', 'Libro'), ('proyecto', 'Proyecto de Grado')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='trabajoinvestigacion',
            name='titulo',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='autortrabajo',
            unique_together={('trabajo', 'autor')},
        ),
    ]
