# Generated by Django 5.2.6 on 2026-02-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0005_alter_autor_options_alter_autortrabajo_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trabajoinvestigacion",
            name="contenido",
            field=models.TextField(blank=True, default=""),
        ),
    ]
