# Generated by Django 5.2.6 on 2026-02-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_trabajoinvestigacion_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajoinvestigacion',
            name='archivo_ruta',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='trabajos/'),
        ),
        migrations.AlterField(
            model_name='trabajoinvestigacion',
            name='titulo',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
