# Generated by Django 5.2.6 on 2026-02-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_alter_trabajoinvestigacion_archivo_ruta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('editorial', models.CharField(blank=True, max_length=100, null=True)),
                ('anio_publicacion', models.PositiveIntegerField(blank=True, null=True)),
                ('numero_edicion', models.PositiveSmallIntegerField(default=1)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('ubicacion_fisica', models.CharField(help_text='Ej: Estante A-3, Fila 2', max_length=100)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas_libros/')),
                ('palabras_clave', models.ManyToManyField(blank=True, to='biblioteca.palabraclave')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo', 'autor'],
            },
        ),
    ]
