# Generated by Django 5.2.6 on 2026-04-08 19:58

from django.db import migrations, models


def copy_publication_year_and_signatura(apps, schema_editor):
    TrabajoInvestigacion = apps.get_model('biblioteca', 'TrabajoInvestigacion')
    Clasificacion = apps.get_model('biblioteca', 'Clasificacion')

    clasificaciones = {
        clasificacion.trabajo_id: clasificacion.signatura_topografica
        for clasificacion in Clasificacion.objects.all()
    }

    for trabajo in TrabajoInvestigacion.objects.all():
        updated_fields = []

        if trabajo.fecha_publicacion:
            trabajo.anio_publicacion = trabajo.fecha_publicacion.year
            updated_fields.append('anio_publicacion')

        signatura = clasificaciones.get(trabajo.pk)
        if signatura:
            trabajo.signatura_topografica = signatura
            updated_fields.append('signatura_topografica')

        if updated_fields:
            trabajo.save(update_fields=updated_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_libro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajoinvestigacion',
            options={'ordering': ['-anio_publicacion', '-created_at'], 'verbose_name': 'Trabajo de Investigación', 'verbose_name_plural': 'Trabajos de Investigación'},
        ),
        migrations.AddField(
            model_name='trabajoinvestigacion',
            name='anio_publicacion',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajoinvestigacion',
            name='signatura_topografica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(copy_publication_year_and_signatura, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='trabajoinvestigacion',
            name='area_modulo',
        ),
        migrations.RemoveField(
            model_name='trabajoinvestigacion',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='trabajoinvestigacion',
            name='estado_validacion',
        ),
        migrations.RemoveField(
            model_name='trabajoinvestigacion',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='trabajoinvestigacion',
            name='institucion_empresa',
        ),
        migrations.RemoveField(
            model_name='trabajoinvestigacion',
            name='nivel_academico',
        ),
        migrations.DeleteModel(
            name='Clasificacion',
        ),
    ]
