# Generated by Django 5.2.6 on 2026-04-10 02:42

from django.db import migrations, models


def copy_authors_and_advisor_text(apps, schema_editor):
    TrabajoInvestigacion = apps.get_model('biblioteca', 'TrabajoInvestigacion')

    for trabajo in TrabajoInvestigacion.objects.all():
        autores = trabajo.autores.all()
        autores_texto = ', '.join(
            f'{autor.nombre} {autor.apellido}'.strip()
            for autor in autores
        )
        asesor = getattr(trabajo, 'asesor', None)
        asesor_texto = ''
        if asesor:
            asesor_texto = f'{asesor.nombre} {asesor.apellido}'.strip()

        trabajo.autores_texto = autores_texto
        trabajo.asesor_texto = asesor_texto
        trabajo.save(update_fields=['autores_texto', 'asesor_texto'])


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_alter_trabajoinvestigacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajoinvestigacion',
            name='asesor_texto',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trabajoinvestigacion',
            name='autores_texto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(copy_authors_and_advisor_text, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='trabajoinvestigacion',
            name='autores',
        ),
        migrations.RemoveField(
            model_name='trabajoinvestigacion',
            name='asesor',
        ),
        migrations.DeleteModel(
            name='AutorTrabajo',
        ),
    ]
