# Generated by Django 5.2.6 on 2026-04-10 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_remove_trabajoinvestigacion_autores_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
