# Generated by Django 5.2.6 on 2026-04-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_delete_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='ubicacion_fisica',
        ),
        migrations.RemoveField(
            model_name='palabraclave',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='trabajoinvestigacion',
            name='objetivo_general',
        ),
        migrations.RemoveField(
            model_name='trabajoinvestigacion',
            name='objetivos_especificos',
        ),
        migrations.AddField(
            model_name='trabajoinvestigacion',
            name='especialidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trabajoinvestigacion',
            name='tipo_material',
            field=models.CharField(choices=[('tesis', 'Tesis'), ('proyecto_grado', 'Proyecto de Grado'), ('trabajo_dirigido', 'Trabajo Dirigido'), ('monografia', 'Monografía'), ('libro', 'Libro')], db_index=True, max_length=50),
        ),
    ]
