# Generated by Django 5.2.6 on 2026-04-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0012_remove_libro_ubicacion_fisica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='documento_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='convocatorias/documentos/'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='imagen_adjunta',
            field=models.ImageField(blank=True, null=True, upload_to='convocatorias/imagenes/'),
        ),
    ]
