# Generated by Django 5.2.6 on 2026-05-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0013_convocatoria_documento_adjunto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='puede_aprobar_prestamos',
        ),
        migrations.DeleteModel(
            name='SolicitudPrestamo',
        ),
    ]
