# Generated by Django 5.2.6 on 2026-06-03 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0014_remove_rol_puede_aprobar_prestamos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajoinvestigacion',
            name='permite_preview_publico',
            field=models.BooleanField(default=True, help_text='Si es True, usuarios no autenticados ven una versión limitada'),
        ),
        migrations.AddField(
            model_name='trabajoinvestigacion',
            name='tipo_preview',
            field=models.CharField(choices=[('paginas', 'Número de páginas'), ('porcentaje', 'Porcentaje del texto')], default='paginas', max_length=20),
        ),
        migrations.AddField(
            model_name='trabajoinvestigacion',
            name='valor_preview',
            field=models.PositiveIntegerField(default=5, help_text='5 páginas o 10% del contenido, según tipo_preview'),
        ),
        migrations.CreateModel(
            name='DocumentoAporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('institucion', models.CharField(blank=True, max_length=200)),
                ('grado_academico', models.CharField(blank=True, max_length=100)),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(upload_to='aportes/%Y/%m/')),
                ('archivo_hash', models.CharField(blank=True, db_index=True, help_text='Hash MD5 del archivo para detectar duplicados', max_length=64)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de verificación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True, help_text='Si fue rechazado, ¿por qué?')),
                ('revisado_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aportes_revisados', to=settings.AUTH_USER_MODEL)),
                ('usuario_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Aporte',
                'verbose_name_plural': 'Documentos Aporte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditoDescarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_externo', models.EmailField(blank=True, max_length=254, null=True)),
                ('token_acceso', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usado_para', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.trabajoinvestigacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditos_descarga', to=settings.AUTH_USER_MODEL)),
                ('aporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='biblioteca.documentoaporte')),
            ],
            options={
                'verbose_name': 'Crédito de Descarga',
                'verbose_name_plural': 'Créditos de Descarga',
            },
        ),
        migrations.CreateModel(
            name='AccesoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_acceso', models.CharField(db_index=True, max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_externos', to='biblioteca.trabajoinvestigacion')),
            ],
            options={
                'verbose_name': 'Acceso Externo',
                'verbose_name_plural': 'Accesos Externos',
                'unique_together': {('token_acceso', 'trabajo')},
            },
        ),
    ]
