# Generated by Django 5.2.6 on 2026-06-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0015_trabajoinvestigacion_permite_preview_publico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajoinvestigacion',
            name='valor_preview',
            field=models.PositiveIntegerField(default=15, help_text='Número de páginas de preview para usuarios externos'),
        ),
    ]
