# Generated by Django 5.2.6 on 2026-06-11 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0016_alter_trabajoinvestigacion_valor_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to='paginas_pdf/%Y/%m/')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='biblioteca.trabajoinvestigacion')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('trabajo', 'numero')},
            },
        ),
    ]
